-- MySQL Script generated by MySQL Workbench
-- Wed Nov  3 16:54:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema piixeldb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema piixeldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `piixeldb` DEFAULT CHARACTER SET utf8 ;
USE `piixeldb` ;

-- -----------------------------------------------------
-- Table `piixeldb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piixeldb`.`Clientes` (
  `Id_Clientes` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(32) NULL,
  `Email` VARCHAR(45) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Telefono` INT NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  `Identificacion` INT NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Clientes`));


-- -----------------------------------------------------
-- Table `piixeldb`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piixeldb`.`Productos` (
  `Id_Producto` INT NOT NULL AUTO_INCREMENT,
  `Marca` VARCHAR(255) NULL,
  `Categoria` VARCHAR(45) NOT NULL,
  `Precio` INT NOT NULL,
  `Ficha_Tecnica_Id_Ficha` INT NOT NULL,
  `Compras_id_compras` INT NOT NULL,
  PRIMARY KEY (`Id_Producto`, `Ficha_Tecnica_Id_Ficha`, `Compras_id_compras`));


-- -----------------------------------------------------
-- Table `piixeldb`.`Compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piixeldb`.`Compras` (
  `id_compras` INT NOT NULL AUTO_INCREMENT,
  `cantidad_productos` INT NOT NULL,
  `fecha_compra` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `precio_total` VARCHAR(45) NULL,
  PRIMARY KEY (`id_compras`));


-- -----------------------------------------------------
-- Table `piixeldb`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piixeldb`.`Administrador` (
  `id_administrador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `apellido` VARCHAR(50) NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` INT NULL,
  `Direccion` VARCHAR(45) NULL,
  `Ciudad` VARCHAR(45) NULL,
  `Documento` INT NOT NULL,
  `Contrasena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_administrador`));


-- -----------------------------------------------------
-- Table `piixeldb`.`Ficha_Tecnica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piixeldb`.`Ficha_Tecnica` (
  `Id_Ficha` INT NOT NULL AUTO_INCREMENT,
  `Marca` VARCHAR(50) NOT NULL,
  `Tecnologia` VARCHAR(32) NOT NULL,
  `RGB` TINYINT NOT NULL,
  `Conectividad` VARCHAR(45) NULL,
  `Capacidad` VARCHAR(45) NULL,
  `Material` VARCHAR(45) NULL,
  `Teclado` VARCHAR(45) NULL,
  `Velocidad` VARCHAR(45) NULL,
  `Mouse` VARCHAR(45) NULL,
  `Monitor` VARCHAR(45) NULL,
  `Chasis` VARCHAR(45) NULL,
  `Fuente` VARCHAR(45) NULL,
  `Procesador` VARCHAR(45) NULL,
  `Placa_Base` VARCHAR(45) NULL,
  `Memoria` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_Ficha`));


-- -----------------------------------------------------
-- Table `piixeldb`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piixeldb`.`Proveedores` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `nit` INT NOT NULL,
  `nombre` VARCHAR(32) NULL,
  `numero_cuenta` INT NOT NULL,
  `telefono` INT NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  PRIMARY KEY (`id_proveedor`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
